version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # depends_on:
    #   - mongodb
    #   - redis
    #   - rabbitmq
    #   - vectordb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6500:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rmqs:/var/lib/rabbitmq

  vectordb:
    image: qdrant/qdrant:v1.1.1
    container_name: vectordb
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  mongo_data:
    driver: local
  qdrant_storage:
    driver: local
  rmqs:
    driver: local
